name: Update Logit Values

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

concurrency:
  # since this runs on an interval this should be fine
  # but we want concurrency failures since we're doing commits
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

jobs:
  update-logit:
    name: Update Logit Values
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Docker
        run: |
          cd ./automation/
          docker compose run --rm nfc_values
          cp "./output/javascript.js" "./../src/app/constants_logit.js"

      - name: Git stuff
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "[Automated] Update logit values"
    
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
